version: '3.9'

services:
  db:
    image: postgres:15-alpine
    container_name: pin_kings_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: eventapp
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: pin_kings_redis
    ports:
      - "6379:6379"

  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    container_name: pin_kings_api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/eventapp
      REDIS_URL: redis://redis:6379/0
    volumes:
      - ./apps/api:/code
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis

  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    container_name: pin_kings_web
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://localhost:8080
    volumes:
      - ./apps/web:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  pgdata:
