name: CI

on:
  push:
    branches: ["main", "work"]
  pull_request:
    branches: ["main"]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install web dependencies
        working-directory: apps/web
        run: |
          npm install
          npm run lint --if-present
          npm test --if-present
          npm run build
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install API dependencies
        working-directory: apps/api
        run: |
          pip install -e .[dev]
          pytest
